//
//  Foursquare.swift
//
//  Foursquare
//
//  Contains:
//  struct Foursquare
//
//  Generated by SwiftPoet on 24/05/2016
//
//

import Foundation

/**
    Foursquare API
*/
public struct Foursquare {
    static public var baseUrl : String = "https://api.foursquare.com/v2"

    public init () {
        
    }

}
