//
//  Venue.swift
//
//  Foursquare
//
//  Contains:
//  struct Venue
//
//  Generated by SwiftPoet on 24/05/2016
//
//

import CleanroomDataTransactions
import Foundation

/**
    Venue
*/
public struct Venue: JSONDataModel, BinaryDataModel {
    // Name
    public let name : String
    // Id
    public let id : String
    // Best photo of venue
    public let bestPhoto : Photo?

    public func toJSON () -> ApidocJSONEncoderResult<AnyObject> {
        
        var resultJSON = [String : AnyObject]()
        resultJSON["name"] = name
        resultJSON["id"] = id
        if let bestPhoto = bestPhoto {
            switch bestPhoto.toJSON() {
                case .Succeeded(let json) :
                
                    resultJSON["bestPhoto"] = json
                case .Failed :
                
                    return .Failed(DataTransactionError.DataFormatError("Invalid Photo? data"))
            }
        }
        return .Succeeded(resultJSON)
    }

    /**
        :param:    payload
    */
    public init (payload : NSDictionary) throws {
        
        let name = try payload.requiredString("name")
        let id = try payload.requiredString("id")
        
        var bestPhoto: Photo? = nil
        if let bestPhotoJson = payload["bestPhoto"] as? NSDictionary {
            bestPhoto = try Photo(payload: bestPhotoJson)
        }

        self.init( name : name, id : id, bestPhoto : bestPhoto )
    }

    /**
        :param:    name Name

        :param:    id Id

        :param:    bestPhoto Best photo of venue
    */
    public init (name : String, id : String, bestPhoto : Photo?) {
        
        self.name = name
        self.id = id
        self.bestPhoto = bestPhoto
    }

}
