//
//  VenueGroup.swift
//
//  Foursquare
//
//  Contains:
//  struct VenueGroup
//
//  Generated by SwiftPoet on 24/05/2016
//
//

import CleanroomDataTransactions
import Foundation

/**
    Venue group
*/
public struct VenueGroup: JSONDataModel, BinaryDataModel {
    // Venue item
    public let items : [VenueItem]

    public func toJSON () -> ApidocJSONEncoderResult<AnyObject> {
        
        var resultJSON = [String : AnyObject]()
        switch items.toJSON() {
            case .Succeeded(let json) :
            
                resultJSON["items"] = json
            case .Failed :
            
                return .Failed(DataTransactionError.DataFormatError("Invalid venue_item data"))
        }
        return .Succeeded(resultJSON)
    }

    /**
        :param:    payload
    */
    public init (payload : NSDictionary) throws {
        
        
        let items = try payload.requiredArrayWithType("items") {
            ( json: NSDictionary ) throws -> VenueItem in
                try VenueItem(payload: json)
        }

        self.init( items : items )
    }

    /**
        :param:    items Venue item
    */
    public init (items : [VenueItem]) {
        
        self.items = items
    }

}
