//
//  VenueExploreResponseWrapper.swift
//
//  Foursquare
//
//  Contains:
//  struct VenueExploreResponseWrapper
//
//  Generated by SwiftPoet on 24/05/2016
//
//

import CleanroomDataTransactions
import Foundation

/**
    Explore venue response wrapper
*/
public struct VenueExploreResponseWrapper: JSONDataModel, BinaryDataModel {
    // Response content
    public let response : VenueExploreResponse

    public func toJSON () -> ApidocJSONEncoderResult<AnyObject> {
        
        var resultJSON = [String : AnyObject]()
        switch response.toJSON() {
            case .Succeeded(let json) :
            
                resultJSON["response"] = json
            case .Failed :
            
                return .Failed(DataTransactionError.DataFormatError("Invalid VenueExploreResponse data"))
        }
        return .Succeeded(resultJSON)
    }

    /**
        :param:    payload
    */
    public init (payload : NSDictionary) throws {
        
        let responseJson = try payload.requiredDictionary("response")
        let response = try VenueExploreResponse(payload: responseJson)

        self.init( response : response )
    }

    /**
        :param:    response Response content
    */
    public init (response : VenueExploreResponse) {
        
        self.response = response
    }

}
