//
//  VenueDetailsResponseWrapper.swift
//
//  Foursquare
//
//  Contains:
//  struct VenueDetailsResponseWrapper
//
//  Generated by SwiftPoet on 24/05/2016
//
//

import CleanroomDataTransactions
import Foundation

/**
    Venue details response wrapper
*/
public struct VenueDetailsResponseWrapper: JSONDataModel, BinaryDataModel {
    public let response : VenueDetailsResponse

    public func toJSON () -> ApidocJSONEncoderResult<AnyObject> {
        
        var resultJSON = [String : AnyObject]()
        switch response.toJSON() {
            case .Succeeded(let json) :
            
                resultJSON["response"] = json
            case .Failed :
            
                return .Failed(DataTransactionError.DataFormatError("Invalid VenueDetailsResponse data"))
        }
        return .Succeeded(resultJSON)
    }

    /**
        :param:    payload
    */
    public init (payload : NSDictionary) throws {
        
        let responseJson = try payload.requiredDictionary("response")
        let response = try VenueDetailsResponse(payload: responseJson)

        self.init( response : response )
    }

    /**
        :param:    response
    */
    public init (response : VenueDetailsResponse) {
        
        self.response = response
    }

}
