//
//  VenueExploreResponse.swift
//
//  Foursquare
//
//  Contains:
//  struct VenueExploreResponse
//
//  Generated by SwiftPoet on 24/05/2016
//
//

import CleanroomDataTransactions
import Foundation

/**
    Explore venue response
*/
public struct VenueExploreResponse: JSONDataModel, BinaryDataModel {
    // List of venue groups i.e. Recommended Places
    public let groups : [VenueGroup]

    public func toJSON () -> ApidocJSONEncoderResult<AnyObject> {
        
        var resultJSON = [String : AnyObject]()
        switch groups.toJSON() {
            case .Succeeded(let json) :
            
                resultJSON["groups"] = json
            case .Failed :
            
                return .Failed(DataTransactionError.DataFormatError("Invalid venue_group data"))
        }
        return .Succeeded(resultJSON)
    }

    /**
        :param:    payload
    */
    public init (payload : NSDictionary) throws {
        
        
        let groups = try payload.requiredArrayWithType("groups") {
            ( json: NSDictionary ) throws -> VenueGroup in
                try VenueGroup(payload: json)
        }

        self.init( groups : groups )
    }

    /**
        :param:    groups List of venue groups i.e. Recommended Places
    */
    public init (groups : [VenueGroup]) {
        
        self.groups = groups
    }

}
