//
//  VenueGetVenuesExplore.swift
//
//  Foursquare
//
//  Contains:
//  class VenueGetVenuesExplore
//
//  Generated by SwiftPoet on 24/05/2016
//
//

import CleanroomDataTransactions
import CleanroomConcurrency
import Foundation

/**
    Fetches venues nearby for a given query
*/
public class VenueGetVenuesExplore: WrappingDataTransaction {
    public typealias MetadataType = WrappedTransactionType.MetadataType
    public typealias Result = TransactionResult<DataType, MetadataType>
    public typealias Callback = (Result) -> Void
    public typealias DataType = VenueExploreResponseWrapper
    public typealias WrappedTransactionType = ApiDocDictionaryTransaction
    public let wrappedTransaction : WrappedTransactionType?

    /**
        :param:    clientId

        :param:    clientSecret

        :param:    v Version parameter

        :param:    near Search near this location

        :param:    query What to search for
    */
    public init (clientId : String, clientSecret : String, v : String, near : String, query : String) throws {
        
        let queryParams: [String : String?]? = [
            
            "client_id" : clientId
            , "client_secret" : clientSecret
            , "v" : v
            , "near" : near
            , "query" : query ]

        do {
            let request = NSMutableURLRequest(URL: try VenueGetVenuesExplore.getUrl( queryParams))
            request.HTTPMethod = "GET"

            self.wrappedTransaction = ApiDocDictionaryTransaction(request: request, uploadData: nil)
        }
        catch {
            
            self.wrappedTransaction = nil
            throw error
        }
    }

    static private func getBaseUrl () -> String {
        return Foursquare.baseUrl + "/venues/explore"
    }

    /**
        :param:    queryParams
    */
    static private func getUrl (queryParams : [String:String?]?) throws -> NSURL {
        
        let urlBuilder = NSURLComponents(string: VenueGetVenuesExplore.getBaseUrl( ))

        urlBuilder?.queryItems =  queryParams?.flatMap {
            ( k, v ) -> NSURLQueryItem? in
                
                if v != nil {
                    return NSURLQueryItem(name: k, value: v)
                }
                return nil
        }

        guard let url = urlBuilder?.URL else {
            throw DataTransactionError.InvalidURL(urlBuilder?.string ?? "N/A")
        }

        return url
    }

    /**
        :param:    completion
    */
    public func executeTransaction (completion : Callback) {
        wrappedTransaction?.executeTransaction() {
            ( result ) -> Void in
                switch result {
                    case .Failed(let error) :
                    
                        completion(.Failed(error))
                    case .Succeeded(let payload, let meta) :
                    
                        async {
                            do {
                                
                                let model = try VenueExploreResponseWrapper(payload: payload)
                                completion(.Succeeded(model, meta))
                            }
                            catch {
                                completion(.Failed(.wrap(error)))
                            }
                        }
                }
        }
    }

}
